### PR TITLE
Converted code into python 3

### LINKED ISSUE #28: Please include support for python 3
The current script fails on python 3. 
You can use the library https://docs.python.org/2/library/2to3.html to do the conversion. 

```
$ python -m congressionalrecord.cli -h
Traceback (most recent call last):
  File "/homed/content/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/homed/content/anaconda3/lib/python3.6/runpy.py", line 153, in _get_module_details
    code = loader.get_code(mod_name)
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/homed/content/anaconda3/lib/python3.6/site-packages/congressionalrecord/cli.py", line 69
    print "Haven't written the hooks for other functionality yet."
                                                                 ^
SyntaxError: Missing parentheses in call to 'print'

```

### PR DESCRIPTION
**Pull request by napsternxg**
Run the following command:

```
2to3 --output-dir=congressional-record-py3 \
-W -n -f all -f idioms \
congressional-record/
```

Fix a test case for test_content_length

Fixes #28

### CODE REVIEW

**Comment by AlJohri** [comment]
@napsternxg I don't think you can use 2to3 for this to maintain backward compatibility. For example, this PR is missing `__future__` imports

**Comment by napsternxg** [comment]
Hi @AlJohri yes, thanks for pointing it out. I know that. I just needed support for python3. Adding compatibility will require some more work. But this branch can be a way to move forward from there. This was the best quick fix I could do right now to get my things running. Would you like to clean this up to include compatibility with python2 ?

**Comment by AlJohri** [comment]
sure, I'll give it a go. for future reference, this command should get you up and running with backward compatibility pretty quickly: `futurize --both-stages --write --nobackups congressionalrecord`

**Comment by napsternxg** [comment]
@AlJohri thanks. Is this a separate package or is it preinstalled with python ?

**Comment by AlJohri** [comment]
http://python-future.org/

**Comment by napsternxg** [comment]
Ya just had a look at it. Thanks this was helpful. I will try it out and make an update to this PR sometime later.

**Comment by nclarkjudd** [comment]
Thank you @AlJohri @napsternxg for these contributions. I will let this PR sit a few days to see if @napsternxg has a chance to do a little more wrt backward compatibility.

**Comment by AlJohri** [comment]
@nclarkjudd fixed in #32

**Comment by napsternxg** [comment]
This is great thanks @AlJohri. Do you think I should close this PR, since your PR is actually a better version of it ?

**Comment by AlJohri** [comment]
up to @napsternxg, but I think that makes sense. thanks for getting this started though!!

**Pull request closed without merging**
